CREATE TABLE IF NOT EXISTS transfer_plant
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tanggal_dikirim VARCHAR(30),
    no_dokumen      VARCHAR(30),
    nama_barang     VARCHAR(30),
    quantity_barang VARCHAR(30),
    outlet_penerima VARCHAR(30),
    outlet_pengirim VARCHAR(30),
    mod_incharge    VARCHAR(30),
    uom             VARCHAR(255),
    user_id         BIGINT,
    CONSTRAINT pk_transferplant PRIMARY KEY (id)
);

ALTER TABLE transfer_plant
    ADD CONSTRAINT uc_transferplant_id UNIQUE (id);

ALTER TABLE transfer_plant
    ADD CONSTRAINT FK_TRANSFERPLANT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);