CREATE TABLE IF NOT EXISTS asset
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    no_assets        VARCHAR(30),
    tanggal_diterima VARCHAR(30),
    nama             VARCHAR(30),
    quantity         VARCHAR(30),
    harga_assets     DECIMAL,
    tanggal_input    VARCHAR(30),
    vendor           VARCHAR(255),
    jenis            VARCHAR(255),
    user_id          BIGINT,
    CONSTRAINT pk_asset PRIMARY KEY (id)
);

ALTER TABLE asset
    ADD CONSTRAINT FK_ASSET_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);