CREATE TABLE IF NOT EXISTS users_roles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    role_id          BIGINT,
    CONSTRAINT pk_users_roles PRIMARY KEY (id)
);
ALTER TABLE users_roles
    ADD CONSTRAINT uc_users_roles_id UNIQUE(id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE users_roles
    ADD CONSTRAINT FK_USERS_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id);