CREATE TABLE IF NOT EXISTS retur
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nama_barang     VARCHAR(50),
    production_date VARCHAR(30),
    exp_date        VARCHAR(30),
    jumlah_retur    VARCHAR(30),
    code_barang     VARCHAR(30),
    tanggal_retur   VARCHAR(255),
    deskripsi       VARCHAR(100),
    vendor          VARCHAR(255),
    negara          VARCHAR(255),
    uom             VARCHAR(255),
    user_id         BIGINT,
    CONSTRAINT pk_retur PRIMARY KEY (id)
);

ALTER TABLE retur
    ADD CONSTRAINT uc_retur_id UNIQUE (id);

ALTER TABLE retur
    ADD CONSTRAINT FK_RETUR_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);