CREATE TABLE IF NOT EXISTS frozen
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nama_product       VARCHAR(50),
    suhu_product       VARCHAR(10),
    production_date    VARCHAR(30),
    exp_date           VARCHAR(30),
    quantity           VARCHAR(30),
    code_barang        VARCHAR(30),
    tanggal_penerimaan VARCHAR(30),
    deskripsi          VARCHAR(100),
    vendor             VARCHAR(255),
    negara             VARCHAR(255),
    uom                VARCHAR(255),
    user_id            BIGINT,
    CONSTRAINT pk_frozen PRIMARY KEY (id)
);

ALTER TABLE frozen
    ADD CONSTRAINT uc_frozen_id UNIQUE(id);

ALTER TABLE frozen
    ADD CONSTRAINT FK_FROZEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);