CREATE TABLE IF NOT EXISTS users
(
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nama              VARCHAR(255),
    alamat            VARCHAR(255),
    jenis_kelamin     VARCHAR(255),
    pendidikan        VARCHAR(255),
    telephone         VARCHAR(255),
    status_perkawinan VARCHAR(255),
    tanggal_join      VARCHAR(255),
    email             VARCHAR(255),
    username          VARCHAR(255),
    password          VARCHAR(255),
    enabled           BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);