CREATE TABLE IF NOT EXISTS raw
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nama_product       VARCHAR(50),
    production_date    VARCHAR(30),
    exp_date           VARCHAR(30),
    quantity           VARCHAR(30),
    code_barang        VARCHAR(30),
    tanggal_penerimaan VARCHAR(255),
    deskripsi          VARCHAR(100),
    vendor             VARCHAR(255),
    negara             VARCHAR(255),
    uom                VARCHAR(255),
    user_id            BIGINT,
    CONSTRAINT pk_raw PRIMARY KEY (id)
);

ALTER TABLE raw
    ADD CONSTRAINT uc_raw_id UNIQUE (id);

ALTER TABLE raw
    ADD CONSTRAINT FK_RAW_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);